// Shared showcase-path inventory for the page-sweeping specs (console-errors,
// a11y, keyboard-nav, htmx-targets). Source of truth = the URL map in
// HelloResource.java (/components/, /extensions/) plus the demo cards in
// templates/hello.html (/demos/). We can't parse those files at runtime —
// e2e.sh mounts only integration-tests/e2e into the Playwright container — so
// this list is maintained by hand and console-errors' drift guard hard-fails
// whenever it diverges from the live /components grid. Every sweeping spec
// imports from here; per-spec copies are how coverage silently decayed before.

export const COMPONENT_PATHS = [
  "/components/about-modal",
  "/components/accordion",
  "/components/action-list",
  "/components/alert",
  "/components/application-launcher",
  "/components/avatar",
  "/components/backdrop",
  "/components/background-image",
  "/components/back-to-top",
  "/components/badge",
  "/components/banner",
  "/components/brand",
  "/components/breadcrumb",
  "/components/button",
  "/components/calendar-month",
  "/components/card",
  "/components/chart",
  "/components/checkbox",
  "/components/chip",
  "/components/click-to-edit",
  "/components/click-to-load",
  "/components/clipboard-copy",
  "/components/code-block",
  "/components/code-editor",
  "/components/compass",
  "/components/content",
  "/components/context-selector",
  "/components/custom-menus",
  "/components/data-list",
  "/components/date-and-time-picker",
  "/components/date-picker",
  "/components/description-list",
  "/components/divider",
  "/components/document-editor",
  "/components/drag-and-drop",
  "/components/drawer",
  "/components/dropdown",
  "/components/dual-list-selector",
  "/components/empty-state",
  "/components/expandable-section",
  "/components/form",
  "/components/form-control",
  "/components/form-select",
  "/components/form-validation",
  "/components/helper-text",
  "/components/hero",
  "/components/hint",
  "/components/i18n",
  "/components/icon",
  "/components/infinite-scroll",
  "/components/inline-edit",
  "/components/input-group",
  "/components/jump-links",
  "/components/label",
  "/components/lazy-modal",
  "/components/list",
  "/components/live-search",
  "/components/login-page",
  "/components/map",
  "/components/masthead",
  "/components/menu",
  "/components/menu-toggle",
  "/components/modal",
  "/components/multiple-file-upload",
  "/components/navigation",
  "/components/notification-badge",
  "/components/notification-drawer",
  "/components/number-input",
  "/components/options-menu",
  "/components/overflow-menu",
  "/components/page",
  "/components/pagination",
  "/components/panel",
  "/components/password-generator",
  "/components/password-strength",
  "/components/popover",
  "/components/progress",
  "/components/progress-stepper",
  "/components/radio",
  "/components/rectangle-selection",
  "/components/rich-text-editor",
  "/components/ripple",
  "/components/search-input",
  "/components/select",
  "/components/sidebar",
  "/components/simple-file-upload",
  "/components/simple-list",
  "/components/skeleton",
  "/components/skeleton-loading",
  "/components/skip-to-content",
  "/components/slider",
  "/components/sortable-table",
  "/components/spinner",
  "/components/switch",
  "/components/table",
  "/components/tabs",
  "/components/text-area",
  "/components/text-input",
  "/components/text-input-group",
  "/components/tile",
  "/components/time-picker",
  "/components/timestamp",
  "/components/title",
  "/components/toast-confirm",
  "/components/toggle-group",
  "/components/toolbar",
  "/components/tooltip",
  "/components/topology",
  "/components/tree-view",
  "/components/truncate",
  "/components/video-player",
  "/components/wizard",
];

export const EXTENSION_PATHS = [
  "/extensions/log-viewer",
  "/extensions/user-feedback",
  "/extensions/catalog-view/catalog-item-header",
  "/extensions/catalog-view/catalog-tile",
  "/extensions/catalog-view/filter-side-panel",
  "/extensions/catalog-view/properties-side-panel",
  "/extensions/catalog-view/vertical-tabs",
  "/extensions/data-view/overview",
  "/extensions/data-view/toolbar",
  "/extensions/data-view/table",
];

export const DEMO_PATHS = ["/demos/dashboard", "/demos/data-management", "/demos/settings", "/demos/landing"];

// Every showcase card, minus the index itself.
export const SHOWCASE_PATHS = [...COMPONENT_PATHS, ...EXTENSION_PATHS, ...DEMO_PATHS];

// "/" is the home/landing page, "/components" the grid, "/licenses" the attributions page.
export const ALL_PATHS = ["/", "/components", "/licenses", ...SHOWCASE_PATHS];
