package org.sitenetsoft.quarkus.pha.it;

import io.quarkus.qute.TemplateGlobal;
import org.sitenetsoft.quarkus.pha.model.CodeBlock;

/**
 * Demo data for the code-block examples — the examples on
 * /components/code-block are populated from these models (with-copy's
 * clipboard button is generated by the model's withCopy()). Globals so the
 * standalone example route (which renders templates without data) can see
 * them. Each is mirrored by a snippet in resources/code-samples/code-block/
 * served on the example card's Java tab — keep them in sync when editing.
 */
@TemplateGlobal
public class CodeBlockDemoData {

    public static CodeBlock demoCodeBasic = CodeBlock.of("cb-basic",
            "apiVersion: v1\nkind: Pod\nmetadata:\n  name: example\nspec:\n  containers:\n"
                    + "    - name: nginx\n      image: nginx:1.25").build();

    public static CodeBlock demoCodeCopy = CodeBlock.of("cb-copy",
            "curl -X POST https://api.example.com/v1/projects \\\n"
                    + "  -H \"Authorization: Bearer $TOKEN\" \\\n"
                    + "  -d '{\"name\": \"my-project\"}'").withCopy().build();
}
