package org.sitenetsoft.quarkus.pha.it;

import io.quarkus.qute.Template;
import io.quarkus.qute.TemplateInstance;
import jakarta.inject.Inject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

@Path("/")
public class HelloResource {

    @Inject
    Template home;

    @Inject
    Template licenses;

    /**
     * Components without a homepage thumbnail in /web/images/components/.
     * Listed here so the template renders a placeholder instead of an
     * &lt;img&gt; that would 404. Drop an id from this set once a real
     * thumbnail PNG is added.
     */
    private static final Set<String> NO_THUMBNAIL = Set.of(
        "form-validation",
        "toast-confirm",
        "click-to-edit",
        "sortable-table",
        "skeleton-loading",
        "hero",
        "compass",
        "catalog-item-header",
        "catalog-tile",
        "chart",
        "data-view-overview",
        "data-view-toolbar",
        "data-view-table",
        "document-editor",
        "filter-side-panel",
        "i18n",
        "log-viewer",
        "map",
        "properties-side-panel",
        "rectangle-selection",
        "rich-text-editor",
        "ripple",
        "topology",
        "user-feedback",
        "vertical-tabs",
        "video-player"
    );

    /** Components that have a working demo page. */
    private static final Map<String, String> IMPLEMENTED = Map.ofEntries(
        Map.entry("about-modal",      "/components/about-modal"),
        Map.entry("accordion",        "/components/accordion"),
        Map.entry("action-list",      "/components/action-list"),
        Map.entry("alert",            "/components/alert"),
        Map.entry("avatar",           "/components/avatar"),
        Map.entry("back-to-top",      "/components/back-to-top"),
        Map.entry("backdrop",         "/components/backdrop"),
        Map.entry("background-image", "/components/background-image"),
        Map.entry("badge",            "/components/badge"),
        Map.entry("banner",           "/components/banner"),
        Map.entry("brand",            "/components/brand"),
        Map.entry("breadcrumb",       "/components/breadcrumb"),
        Map.entry("button",           "/components/button"),
        Map.entry("calendar-month",   "/components/calendar-month"),
        Map.entry("card",             "/components/card"),
        Map.entry("checkbox",         "/components/checkbox"),
        Map.entry("chip",             "/components/chip"),
        Map.entry("clipboard-copy",   "/components/clipboard-copy"),
        Map.entry("code-block",       "/components/code-block"),
        Map.entry("code-editor",      "/components/code-editor"),
        Map.entry("content",          "/components/content"),
        Map.entry("context-selector", "/components/context-selector"),
        Map.entry("custom-menus",     "/components/custom-menus"),
        Map.entry("divider",          "/components/divider"),
        Map.entry("empty-state",      "/components/empty-state"),
        Map.entry("expandable-section", "/components/expandable-section"),
        Map.entry("helper-text",      "/components/helper-text"),
        Map.entry("hint",             "/components/hint"),
        Map.entry("icon",             "/components/icon"),
        Map.entry("label",            "/components/label"),
        Map.entry("list",             "/components/list"),
        Map.entry("panel",            "/components/panel"),
        Map.entry("progress",         "/components/progress"),
        Map.entry("ripple",           "/components/ripple"),
        Map.entry("i18n",             "/components/i18n"),
        Map.entry("skeleton",         "/components/skeleton"),
        Map.entry("spinner",          "/components/spinner"),
        Map.entry("timestamp",        "/components/timestamp"),
        Map.entry("title",            "/components/title"),
        Map.entry("truncate",         "/components/truncate"),
        Map.entry("data-list",        "/components/data-list"),
        Map.entry("description-list", "/components/description-list"),
        Map.entry("form",             "/components/form"),
        Map.entry("form-control",     "/components/form-control"),
        Map.entry("form-select",      "/components/form-select"),
        Map.entry("number-input",     "/components/number-input"),
        Map.entry("radio",            "/components/radio"),
        Map.entry("switch",           "/components/switch"),
        Map.entry("text-area",        "/components/text-area"),
        Map.entry("text-input",       "/components/text-input"),
        Map.entry("text-input-group", "/components/text-input-group"),
        Map.entry("toggle-group",     "/components/toggle-group"),
        Map.entry("simple-list",      "/components/simple-list"),
        Map.entry("simple-file-upload", "/components/simple-file-upload"),
        Map.entry("tile",             "/components/tile"),
        Map.entry("hero",             "/components/hero"),
        Map.entry("compass",          "/components/compass"),
        Map.entry("date-picker",      "/components/date-picker"),
        Map.entry("dropdown",         "/components/dropdown"),
        Map.entry("drawer",           "/components/drawer"),
        Map.entry("inline-edit",      "/components/inline-edit"),
        Map.entry("input-group",      "/components/input-group"),
        Map.entry("jump-links",       "/components/jump-links"),
        Map.entry("menu",             "/components/menu"),
        Map.entry("menu-toggle",      "/components/menu-toggle"),
        Map.entry("modal",            "/components/modal"),
        Map.entry("notification-badge", "/components/notification-badge"),
        Map.entry("notification-drawer", "/components/notification-drawer"),
        Map.entry("overflow-menu",    "/components/overflow-menu"),
        Map.entry("popover",          "/components/popover"),
        Map.entry("tooltip",          "/components/tooltip"),
        Map.entry("progress-stepper", "/components/progress-stepper"),
        Map.entry("login-page",      "/components/login-page"),
        Map.entry("masthead",        "/components/masthead"),
        Map.entry("navigation",      "/components/navigation"),
        Map.entry("page",            "/components/page"),
        Map.entry("pagination",      "/components/pagination"),
        Map.entry("search-input",    "/components/search-input"),
        Map.entry("select",          "/components/select"),
        Map.entry("sidebar",         "/components/sidebar"),
        Map.entry("skip-to-content", "/components/skip-to-content"),
        Map.entry("slider",          "/components/slider"),
        Map.entry("tabs",            "/components/tabs"),
        Map.entry("toolbar",         "/components/toolbar"),
        Map.entry("tree-view",       "/components/tree-view"),
        Map.entry("wizard",          "/components/wizard"),
        Map.entry("application-launcher", "/components/application-launcher"),
        Map.entry("date-and-time-picker", "/components/date-and-time-picker"),
        Map.entry("drag-and-drop",   "/components/drag-and-drop"),
        Map.entry("dual-list-selector", "/components/dual-list-selector"),
        Map.entry("multiple-file-upload", "/components/multiple-file-upload"),
        Map.entry("options-menu",    "/components/options-menu"),
        Map.entry("password-generator", "/components/password-generator"),
        Map.entry("password-strength", "/components/password-strength"),
        Map.entry("table",           "/components/table"),
        Map.entry("time-picker",     "/components/time-picker"),
        Map.entry("rectangle-selection", "/components/rectangle-selection"),
        Map.entry("map",                "/components/map"),
        Map.entry("document-editor",   "/components/document-editor"),
        Map.entry("chart",             "/components/chart"),
        Map.entry("topology",          "/components/topology"),
        Map.entry("form-validation",   "/components/form-validation"),
        Map.entry("sortable-table",    "/components/sortable-table"),
        Map.entry("click-to-edit",     "/components/click-to-edit"),
        Map.entry("toast-confirm",     "/components/toast-confirm"),
        Map.entry("skeleton-loading",  "/components/skeleton-loading"),
        Map.entry("live-search",       "/components/live-search"),
        Map.entry("infinite-scroll",   "/components/infinite-scroll"),
        Map.entry("click-to-load",     "/components/click-to-load"),
        Map.entry("lazy-modal",        "/components/lazy-modal"),
        Map.entry("video-player",      "/components/video-player"),
        Map.entry("rich-text-editor",  "/components/rich-text-editor"),
        Map.entry("log-viewer",            "/extensions/log-viewer"),
        Map.entry("user-feedback",         "/extensions/user-feedback"),
        Map.entry("catalog-item-header",   "/extensions/catalog-view/catalog-item-header"),
        Map.entry("catalog-tile",          "/extensions/catalog-view/catalog-tile"),
        Map.entry("filter-side-panel",     "/extensions/catalog-view/filter-side-panel"),
        Map.entry("properties-side-panel", "/extensions/catalog-view/properties-side-panel"),
        Map.entry("vertical-tabs",         "/extensions/catalog-view/vertical-tabs"),
        Map.entry("data-view-overview",    "/extensions/data-view/overview"),
        Map.entry("data-view-toolbar",     "/extensions/data-view/toolbar"),
        Map.entry("data-view-table",       "/extensions/data-view/table")
    );

    /** Components tagged with a footer label. */
    private static final Map<String, String> LABELS = Map.ofEntries(
        Map.entry("application-launcher", "Demo"),
        Map.entry("chip",                 "Deprecated"),
        Map.entry("context-selector",     "Demo"),
        Map.entry("custom-menus",         "Demo"),
        Map.entry("date-and-time-picker", "Demo"),
        Map.entry("dropdown",             "Beta"),
        Map.entry("options-menu",         "Demo"),
        Map.entry("password-generator",   "Demo"),
        Map.entry("password-strength",    "Demo"),
        Map.entry("select",               "Beta"),
        Map.entry("rectangle-selection",  "Custom"),
        Map.entry("map",                "Custom"),
        Map.entry("document-editor",   "Custom"),
        Map.entry("chart",             "Custom"),
        Map.entry("topology",          "Custom"),
        Map.entry("form-validation",   "HTMX"),
        Map.entry("sortable-table",    "HTMX"),
        Map.entry("click-to-edit",     "HTMX"),
        Map.entry("toast-confirm",     "HTMX"),
        Map.entry("skeleton-loading",  "HTMX"),
        Map.entry("live-search",       "HTMX"),
        Map.entry("infinite-scroll",   "HTMX"),
        Map.entry("click-to-load",     "HTMX"),
        Map.entry("lazy-modal",        "HTMX"),
        Map.entry("video-player",      "Custom"),
        Map.entry("rich-text-editor",  "Custom"),
        Map.entry("ripple",            "Custom"),
        Map.entry("i18n",              "Custom"),
        Map.entry("log-viewer",            "Extension"),
        Map.entry("user-feedback",         "Extension"),
        Map.entry("catalog-item-header",   "Extension"),
        Map.entry("catalog-tile",          "Extension"),
        Map.entry("filter-side-panel",     "Extension"),
        Map.entry("properties-side-panel", "Extension"),
        Map.entry("vertical-tabs",         "Extension"),
        Map.entry("data-view-overview",    "Extension"),
        Map.entry("data-view-toolbar",     "Extension"),
        Map.entry("data-view-table",       "Extension")
    );

    /** Label text → PF label color modifier. */
    private static final Map<String, String> LABEL_COLORS = Map.of(
        "Demo",       "pf-m-purple",
        "Beta",       "pf-m-blue",
        "Deprecated", "",
        "Custom",     "pf-m-teal",
        "HTMX",       "pf-m-green",
        "Extension",  "pf-m-orange"
    );

    /** Deprecated components also need "Tile". */
    private static final Set<String> DEPRECATED = Set.of("chip", "tile");

    /** One-line, PatternFly-style descriptions shown in the /components list view. */
    private static final Map<String, String> DESCRIPTIONS = Map.ofEntries(
        Map.entry("about-modal", "An about modal displays information about an application, like product version numbers and any appropriate legal text."),
        Map.entry("accordion", "An accordion is a vertically stacked list that can be expanded and collapsed to reveal and hide nested content."),
        Map.entry("action-list", "An action list is a group of actions, controls, or buttons with built-in spacing."),
        Map.entry("alert", "An alert is a non-intrusive notification that shares brief, important messages with users."),
        Map.entry("application-launcher", "An application launcher is a menu that provides quick access to a set of related applications or tools."),
        Map.entry("avatar", "An avatar is a visual representation of a user, which can contain an image or placeholder graphic."),
        Map.entry("back-to-top", "The back to top component is a shortcut that allows users to quickly navigate to the top of a page via a button."),
        Map.entry("backdrop", "A backdrop is a screen that covers the main content of a page when a modal is opened, to prevent page interaction until the modal is dismissed."),
        Map.entry("background-image", "A background image is an image that fills the background of a page."),
        Map.entry("badge", "A badge is an annotation that displays a numeric value."),
        Map.entry("banner", "A banner is a short message that is shared with users in an unobtrusive, full-width container that cannot be dismissed."),
        Map.entry("brand", "A brand is a visual representation of a product—typically its logo."),
        Map.entry("breadcrumb", "A breadcrumb is a secondary navigation method that shows where users are in an application, to help them navigate more efficiently."),
        Map.entry("button", "A button is an object that communicates and triggers an action when it is clicked or selected."),
        Map.entry("calendar-month", "A calendar month displays a single month and allows users to select a date."),
        Map.entry("card", "A card is a content container that displays entry-level information—typically within dashboards, galleries, and catalogs."),
        Map.entry("catalog-item-header", "A catalog item header displays the title, icon, and metadata at the top of a catalog item detail view."),
        Map.entry("catalog-tile", "A catalog tile is a selectable card that presents a single item within a catalog view."),
        Map.entry("chart", "A chart visualizes data sets as bar, line, area, pie, and other graph types."),
        Map.entry("checkbox", "A checkbox is used to select one or more items from a list, or to turn an option on or off."),
        Map.entry("chip", "A chip is used to communicate a value or a set of attribute-value pairs within workflows that involve filtering a set of objects."),
        Map.entry("click-to-load", "Click to load appends the next set of results to a list when a user selects a load-more button."),
        Map.entry("clipboard-copy", "The clipboard copy component allows users to quickly and easily copy content to their clipboard."),
        Map.entry("code-block", "A code block contains 2 or more lines of read-only code, which can be copied to a user's clipboard."),
        Map.entry("code-editor", "A code editor is a versatile Monaco-based text editor that supports various programming languages."),
        Map.entry("content", "A content component contains a block of styled HTML content."),
        Map.entry("context-selector", "A context selector allows users to switch between distinct contexts, such as projects or environments."),
        Map.entry("custom-menus", "Custom menus compose the menu building blocks into bespoke dropdown, select, and action patterns."),
        Map.entry("data-list", "A data list displays large data sets and interactive content in a flexible layout."),
        Map.entry("data-view-overview", "The data view is a composable pattern for presenting data sets with a toolbar, table or card layout, and pagination."),
        Map.entry("data-view-toolbar", "A data view toolbar provides search, filtering, and view controls for a data view."),
        Map.entry("data-view-table", "A data view table renders a data set as a sortable, selectable table within a data view."),
        Map.entry("date-and-time-picker", "A date and time picker combines a date picker and a time picker to select a full date and time value."),
        Map.entry("date-picker", "A date picker is a text input with a calendar dropdown that allows users to select a date."),
        Map.entry("description-list", "A description list displays terms and their corresponding descriptions."),
        Map.entry("divider", "A divider is a horizontal or vertical line that is placed between screen elements to create visual divisions and content groupings."),
        Map.entry("document-editor", "A document editor embeds a Collabora Online editor for viewing and editing documents, spreadsheets, and presentations."),
        Map.entry("drag-and-drop", "The drag and drop component allows users to reposition, rearrange, and group items into more relevant and appropriate layouts."),
        Map.entry("drawer", "A drawer is a sliding panel that enters from outside of the viewport, which can be configured to either overlay content or create a sidebar by pushing content."),
        Map.entry("dropdown", "A dropdown presents a menu of actions or links in a constrained space by toggling their visibility."),
        Map.entry("dual-list-selector", "A dual list selector displays 2 interactive lists: a list of selected items and a list of available, selectable items. Users can move items between the lists."),
        Map.entry("empty-state", "An empty state is a screen that is not yet populated with data or information—typically containing a short message and next steps for users."),
        Map.entry("expandable-section", "An expandable section is a content section with a text toggle that reveals content that is hidden by default."),
        Map.entry("filter-side-panel", "A filter side panel presents grouped, selectable filters alongside a catalog or data view."),
        Map.entry("form", "A form is a group of related fields, inputs, and controls that users complete and submit."),
        Map.entry("form-control", "A form control provides the base styling for text inputs, selects, and other form fields."),
        Map.entry("form-select", "A form select is a styled native select element for choosing a single option from a list."),
        Map.entry("helper-text", "Helper text is a text-based support method that adds additional context to field inputs."),
        Map.entry("hint", "A hint is an in-app message that shares reminders, explanations, or calls to action within a page."),
        Map.entry("icon", "An icon component is a container that supports icons of varying dimensions and styles, as well as spinners."),
        Map.entry("infinite-scroll", "Infinite scroll loads additional results automatically as the user scrolls toward the end of a list."),
        Map.entry("inline-edit", "An inline edit component allows users to switch between read-only and edit views of description lists, page text elements, or tables—within the context of their current view."),
        Map.entry("input-group", "An input group combines multiple related controls or inputs to appear as a single control."),
        Map.entry("jump-links", "When clicked, jump links allow users to navigate to sections within a page without scrolling."),
        Map.entry("label", "A label is a descriptive annotation that adds context to an element for clarity and convenience."),
        Map.entry("lazy-modal", "A lazy modal fetches its contents from the server the first time it is opened."),
        Map.entry("list", "A list component embeds a formatted list—bulleted or numbered—into page content."),
        Map.entry("form-validation", "Form validation gives users immediate, server-driven feedback about the values they enter into a form."),
        Map.entry("sortable-table", "A sortable table reorders its rows when a user selects a column header, with sorting handled on the server."),
        Map.entry("click-to-edit", "Click to edit swaps a read-only value for an editable field in place when the user selects it."),
        Map.entry("toast-confirm", "Toast confirm pairs a confirmation dialog with a toast notification to acknowledge a completed action."),
        Map.entry("skeleton-loading", "Skeleton loading shows placeholder shapes while content is fetched, then swaps in the real content."),
        Map.entry("live-search", "Live search updates a list of results as the user types, querying the server on each change."),
        Map.entry("log-viewer", "A log viewer displays streaming or static log output with search and line controls."),
        Map.entry("login-page", "A login page allows a user to access an application by entering a username and password, or by authenticating using a social media login."),
        Map.entry("map", "A map is an interactive, pannable map built on MapLibre for plotting markers and overlays."),
        Map.entry("masthead", "A masthead contains and organizes global properties like a logo, navigation, and settings for easy and consistent access across all pages of an application."),
        Map.entry("menu", "A menu is a list of options or actions that users can choose from."),
        Map.entry("menu-toggle", "A menu toggle is the button that opens and closes a menu, dropdown, or select."),
        Map.entry("modal", "A modal is a window that overlays a page to display important information, without requiring users to navigate to a new page."),
        Map.entry("multiple-file-upload", "A multiple file upload allows users to add several files at once by dragging them onto a drop zone or browsing."),
        Map.entry("navigation", "A navigation component organizes and communicates an application's structure and content in a central location, making it easy to find information and accomplish tasks."),
        Map.entry("notification-badge", "A notification badge is a visual indicator that alerts users about incoming notifications."),
        Map.entry("notification-drawer", "A notification drawer contains an application's notifications, which users can view and manage without having to navigate to a new screen."),
        Map.entry("number-input", "A number input combines a text input field with buttons to provide users with a quick and effective way to enter and modify a numeric value."),
        Map.entry("options-menu", "An options menu presents a set of selectable options, such as sort or display settings, in a dropdown."),
        Map.entry("overflow-menu", "An overflow menu groups a set of actions into a responsive horizontal list to help declutter the UI."),
        Map.entry("page", "A page component defines the basic layout of a page, with either vertical or horizontal navigation."),
        Map.entry("pagination", "A pagination component allows users to navigate through large content views that have been split across multiple pages."),
        Map.entry("panel", "A panel is a customizable container that can contain other components in flexible content layouts."),
        Map.entry("password-generator", "This demo demonstrates how to create an input field that generates unique passwords."),
        Map.entry("password-strength", "This demo demonstrates how to validate and display feedback about password strength."),
        Map.entry("popover", "A popover is a small overlay window that provides additional information about an on-screen element."),
        Map.entry("progress", "A progress component is a horizontal bar that indicates the completion status of an ongoing process or task."),
        Map.entry("progress-stepper", "A progress stepper displays a timeline of tasks in a workflow and tracks a user's progress through the workflow."),
        Map.entry("properties-side-panel", "A properties side panel lists an item's attributes as a set of property-value pairs beside the main content."),
        Map.entry("radio", "A radio button is used to select a single option from a set of mutually exclusive choices."),
        Map.entry("rectangle-selection", "Rectangle selection lets users select multiple items by dragging a selection rectangle over them."),
        Map.entry("rich-text-editor", "A rich text editor is a Quill-based editor for composing formatted text content."),
        Map.entry("ripple", "Ripple is a lightweight, pure-CSS loading indicator built from animated expanding rings."),
        Map.entry("i18n", "The i18n demo shows how server-rendered components pick up translated messages from a message bundle."),
        Map.entry("search-input", "A search input is a type of input field that can be used to search, find, or filter."),
        Map.entry("select", "A select presents a menu of options within a form, allowing users to choose one or more values."),
        Map.entry("sidebar", "A sidebar is a panel that splits content into a secondary area within a page."),
        Map.entry("simple-file-upload", "A simple file upload provides a single-file input with a filename display and browse and clear controls."),
        Map.entry("simple-list", "A simple list displays selectable items within a page."),
        Map.entry("skeleton", "A skeleton is a type of loading state that allows you to expose content incrementally."),
        Map.entry("skip-to-content", "A skip to content component allows users to bypass navigation when using a screen reader or keyboard."),
        Map.entry("slider", "A slider is an interactive element that allows users to quickly set and adjust a numeric value from a defined range of values."),
        Map.entry("spinner", "A spinner is an animated visual that indicates when a quick action is in progress."),
        Map.entry("switch", "A switch is a control that toggles the state of a setting between on and off."),
        Map.entry("table", "A table displays large data sets in a simple grid with column headers."),
        Map.entry("tabs", "Tabs group similar content within sub-views of a page."),
        Map.entry("text-area", "A text area is a multi-line text input for longer, free-form content."),
        Map.entry("text-input", "A text input is a single-line field for entering and editing short text values."),
        Map.entry("text-input-group", "A text input group is a more custom, flexible, and composable version of a text input that includes elements like icons and buttons."),
        Map.entry("tile", "A tile is a container that allows users to select a static option."),
        Map.entry("hero", "A hero is a prominent, page-level banner used to introduce a landing or overview page."),
        Map.entry("compass", "Compass is a full-viewport layout for generative and conversational UIs, with a header, optional sidebars, main content, and a footer area that often uses a ChatBot message bar."),
        Map.entry("time-picker", "A time picker is a text input with a dropdown that allows users to select a time of day."),
        Map.entry("timestamp", "A timestamp is a consistently formatted visual that displays date and time values."),
        Map.entry("title", "A title component applies top and bottom margins, font-weight, font-size, and line-height to page and section headings."),
        Map.entry("toggle-group", "A toggle group is a set of controls that can be used to quickly switch between actions or states."),
        Map.entry("toolbar", "A toolbar is a responsive container that displays controls that allow users to manage and manipulate a data set."),
        Map.entry("tooltip", "A tooltip is a small, temporary, overlay window that provides additional information about an on-screen element."),
        Map.entry("topology", "A topology visualizes nodes and their relationships as an interactive graph."),
        Map.entry("tree-view", "A tree view is a structure that displays data in a hierarchical view."),
        Map.entry("truncate", "A truncate component can be used to shorten character strings—typically when the string overflows its container."),
        Map.entry("user-feedback", "A user feedback modal collects ratings and comments from users about their experience."),
        Map.entry("vertical-tabs", "Vertical tabs group related content into panels selected from a vertical list of tabs."),
        Map.entry("video-player", "A video player embeds and controls video playback with a Video.js-based player."),
        Map.entry("wizard", "A wizard is a guided workflow that helps users complete complex tasks, create objects, or follow a series of steps.")
    );

    private static final String[][] COMPONENT_DATA = {
        {"about-modal",          "About modal"},
        {"accordion",            "Accordion"},
        {"action-list",          "Action list"},
        {"alert",                "Alert"},
        {"application-launcher", "Application launcher"},
        {"avatar",               "Avatar"},
        {"back-to-top",          "Back to top"},
        {"backdrop",             "Backdrop"},
        {"background-image",     "Background image"},
        {"badge",                "Badge"},
        {"banner",               "Banner"},
        {"brand",                "Brand"},
        {"breadcrumb",           "Breadcrumb"},
        {"button",               "Button"},
        {"calendar-month",       "Calendar month"},
        {"card",                 "Card"},
        {"catalog-item-header",  "Catalog item header"},
        {"catalog-tile",         "Catalog tile"},
        {"chart",                "Chart"},
        {"checkbox",             "Checkbox"},
        {"chip",                 "Chip"},
        {"click-to-load",        "Click to load"},
        {"clipboard-copy",       "Clipboard copy"},
        {"code-block",           "Code block"},
        {"code-editor",          "Code editor"},
        {"content",              "Content"},
        {"context-selector",     "Context selector"},
        {"custom-menus",         "Custom menus"},
        {"data-list",            "Data list"},
        {"data-view-overview",   "Data view overview"},
        {"data-view-toolbar",    "Data view toolbar"},
        {"data-view-table",      "Data view table"},
        {"date-and-time-picker", "Date and time picker"},
        {"date-picker",          "Date picker"},
        {"description-list",     "Description list"},
        {"divider",              "Divider"},
        {"document-editor",      "Document editor"},
        {"drag-and-drop",        "Drag and drop"},
        {"drawer",               "Drawer"},
        {"dropdown",             "Dropdown"},
        {"dual-list-selector",   "Dual list selector"},
        {"empty-state",          "Empty state"},
        {"expandable-section",   "Expandable section"},
        {"filter-side-panel",    "Filter side panel"},
        {"form",                 "Form"},
        {"form-control",         "Form control"},
        {"form-select",          "Form select"},
        {"helper-text",          "Helper text"},
        {"hint",                 "Hint"},
        {"icon",                 "Icon"},
        {"infinite-scroll",      "Infinite scroll"},
        {"inline-edit",          "Inline edit"},
        {"input-group",          "Input group"},
        {"jump-links",           "Jump links"},
        {"label",                "Label"},
        {"lazy-modal",           "Lazy modal"},
        {"list",                 "List"},
        {"form-validation",      "Form validation"},
        {"sortable-table",       "Sortable table"},
        {"click-to-edit",        "Click to edit"},
        {"toast-confirm",        "Toast & confirm"},
        {"skeleton-loading",     "Skeleton loading"},
        {"live-search",          "Live search"},
        {"log-viewer",           "Log viewer"},
        {"login-page",           "Login page"},
        {"map",                  "Map"},
        {"masthead",             "Masthead"},
        {"menu",                 "Menu"},
        {"menu-toggle",          "Menu toggle"},
        {"modal",                "Modal"},
        {"multiple-file-upload", "Multiple file upload"},
        {"navigation",           "Navigation"},
        {"notification-badge",   "Notification badge"},
        {"notification-drawer",  "Notification drawer"},
        {"number-input",         "Number input"},
        {"options-menu",         "Options menu"},
        {"overflow-menu",        "Overflow menu"},
        {"page",                 "Page"},
        {"pagination",           "Pagination"},
        {"panel",                "Panel"},
        {"password-generator",   "Password generator"},
        {"password-strength",    "Password strength"},
        {"popover",              "Popover"},
        {"progress",             "Progress"},
        {"progress-stepper",     "Progress stepper"},
        {"properties-side-panel","Properties side panel"},
        {"radio",                "Radio"},
        {"rectangle-selection",  "Rectangle selection"},
        {"rich-text-editor",     "Rich text editor"},
        {"ripple",               "Ripple"},
        {"i18n",                 "Internationalization"},
        {"search-input",         "Search input"},
        {"select",               "Select"},
        {"sidebar",              "Sidebar"},
        {"simple-file-upload",   "Simple file upload"},
        {"simple-list",          "Simple list"},
        {"skeleton",             "Skeleton"},
        {"skip-to-content",      "Skip to content"},
        {"slider",               "Slider"},
        {"spinner",              "Spinner"},
        {"switch",               "Switch"},
        {"table",                "Table"},
        {"tabs",                 "Tabs"},
        {"text-area",            "Text area"},
        {"text-input",           "Text input"},
        {"text-input-group",     "Text input group"},
        {"tile",                 "Tile"},
        {"hero",                 "Hero"},
        {"compass",              "Compass"},
        {"time-picker",          "Time picker"},
        {"timestamp",            "Timestamp"},
        {"title",                "Title"},
        {"toggle-group",         "Toggle group"},
        {"toolbar",              "Toolbar"},
        {"tooltip",              "Tooltip"},
        {"topology",             "Topology"},
        {"tree-view",            "Tree view"},
        {"truncate",             "Truncate"},
        {"user-feedback",        "User feedback"},
        {"vertical-tabs",        "Vertical tabs"},
        {"video-player",         "Video player"},
        {"wizard",               "Wizard"},
    };

    @GET
    @Produces(MediaType.TEXT_HTML)
    public TemplateInstance index() {
        return home.instance();
    }

    @GET
    @Path("/licenses")
    @Produces(MediaType.TEXT_HTML)
    public TemplateInstance licensesPage() {
        return licenses.instance();
    }

    /** Shared component-card data for the /components grid (served by ComponentRoutes). */
    public static List<Map<String, String>> buildComponentList() {
        List<Map<String, String>> components = new ArrayList<>();

        for (String[] entry : COMPONENT_DATA) {
            String id = entry[0];
            String name = entry[1];

            Map<String, String> comp = new HashMap<>();
            comp.put("id", id);
            comp.put("name", name);
            comp.put("description", DESCRIPTIONS.getOrDefault(id, ""));
            if (!NO_THUMBNAIL.contains(id)) {
                comp.put("image", "/web/images/components/" + id + ".png");
            }
            comp.put("href", IMPLEMENTED.getOrDefault(id, "#"));

            String labelText = LABELS.get(id);
            if (labelText == null && DEPRECATED.contains(id)) {
                labelText = "Deprecated";
            }
            comp.put("label", labelText != null ? labelText : "");
            comp.put("labelColor", labelText != null ? LABEL_COLORS.getOrDefault(labelText, "") : "");

            components.add(comp);
        }

        return components;
    }
}
